# -*- coding: utf-8 -*-
"""
analyzer.py
Heuristic email header analysis engine for phishing detection.
No external services required: everything runs offline, based purely on
the headers the user provides (raw text or a .eml file).

Part of E-MailX-Ray.
"""

import re
import email
from email import policy
from email.utils import parseaddr, getaddresses
from difflib import SequenceMatcher
from dataclasses import dataclass, field


# ----------------------------------------------------------------------
# Reference data used by the heuristics
# ----------------------------------------------------------------------

FREE_MAIL_DOMAINS = {
    "gmail.com", "hotmail.com", "outlook.com", "yahoo.com", "live.com",
    "aol.com", "icloud.com", "protonmail.com", "mail.com", "yandex.com",
    "gmx.com", "zoho.com",
}

SUSPICIOUS_TLDS = {
    ".tk", ".ml", ".ga", ".cf", ".gq", ".xyz", ".top", ".club", ".work",
    ".icu", ".click", ".link", ".buzz", ".rest", ".fit", ".loan", ".men",
    ".party", ".review", ".science", ".stream", ".download", ".racing",
}

# Commonly-impersonated brands + their typical "official" domain
KNOWN_BRANDS = {
    "paypal": "paypal.com",
    "amazon": "amazon.com",
    "microsoft": "microsoft.com",
    "google": "google.com",
    "apple": "apple.com",
    "netflix": "netflix.com",
    "bank": None,
    "santander": "santander.com",
    "bbva": "bbva.com",
    "mercadolibre": "mercadolibre.com",
    "mercado pago": "mercadopago.com",
    "irs": "irs.gov",
    "dropbox": "dropbox.com",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "whatsapp": "whatsapp.com",
    "linkedin": "linkedin.com",
    "office365": "office.com",
    "coinbase": "coinbase.com",
    "binance": "binance.com",
}

URGENCY_KEYWORDS = [
    "urgent", "verify your account", "suspended", "click here", "confirm your",
    "invoice attached", "payment overdue", "action required", "account locked",
    "limited time", "unusual activity", "confirm your identity", "update your information",
    "you have won", "claim your prize", "final notice",
]


@dataclass
class Finding:
    rule: str
    detail: str
    weight: int
    severity: str  # "info" | "low" | "medium" | "high"


@dataclass
class AnalysisResult:
    fields: dict = field(default_factory=dict)
    findings: list = field(default_factory=list)
    score: int = 0
    risk_level: str = "Low"

    def add(self, rule, detail, weight, severity):
        self.findings.append(Finding(rule, detail, weight, severity))
        self.score += weight


# ----------------------------------------------------------------------
# Utilities
# ----------------------------------------------------------------------

def _domain_of(address: str) -> str:
    if not address:
        return ""
    _, addr = parseaddr(address)
    if "@" in addr:
        return addr.split("@")[-1].strip().lower()
    return ""


def _similarity(a: str, b: str) -> float:
    return SequenceMatcher(None, a, b).ratio()


def _looks_like_typosquat(domain: str, brand_domain: str) -> bool:
    if not domain or not brand_domain:
        return False
    if domain == brand_domain:
        return False
    # High similarity but not identical => suspicious (e.g. paypa1.com vs paypal.com)
    ratio = _similarity(domain, brand_domain)
    return 0.75 <= ratio < 1.0


def _decode_header_value(raw: str) -> str:
    try:
        from email.header import decode_header
        parts = decode_header(raw)
        decoded = ""
        for text, enc in parts:
            if isinstance(text, bytes):
                decoded += text.decode(enc or "utf-8", errors="replace")
            else:
                decoded += text
        return decoded
    except Exception:
        return raw


def _has_random_looking_label(domain: str, min_len: int = 10, max_vowel_ratio: float = 0.15):
    """
    Detects whether any label of the domain (the part between dots) looks
    randomly generated: long and with very few vowels, typical of
    subdomains auto-generated by spam infrastructure
    (e.g. 'rjttznyzjjzydnillquh.designclub.uk.com'). Returns the suspicious
    label, or None if none is found.
    """
    if not domain:
        return None
    for label in domain.split("."):
        letters = [c for c in label if c.isalpha()]
        if len(letters) >= min_len:
            vowels = sum(1 for c in letters if c.lower() in "aeiou")
            if (vowels / len(letters)) <= max_vowel_ratio:
                return label
    return None


# ----------------------------------------------------------------------
# Main analyzer
# ----------------------------------------------------------------------

_HEADER_LINE_RE = re.compile(r"^[A-Za-z][A-Za-z0-9-]*:\s")
_PGP_MARKERS = (
    "-----BEGIN PGP SIGNED MESSAGE-----",
    "-----BEGIN PGP MESSAGE-----",
)


def _strip_pgp_and_noise(raw_text: str) -> str:
    """
    Some clients (e.g. ProtonMail exporting as .txt) wrap the headers in a
    PGP signature block, or the (encrypted) message body appears right
    after the headers as '-----BEGIN PGP MESSAGE-----'. This function:
      1) If the text STARTS with a PGP wrapper (signature), skips those
         armor lines to reach the real headers.
      2) Cuts off everything that comes after the header block (the first
         blank line), so the parser isn't confused by the
         encrypted/signed body.
    """
    text = raw_text.replace("\r\n", "\n").strip("\n")
    lines = text.split("\n")

    # --- Step 1: if the TEXT STARTS with a PGP wrapper, skip it ---------
    start_idx = 0
    if lines and any(lines[0].strip().startswith(m) for m in _PGP_MARKERS):
        for i, line in enumerate(lines):
            if any(line.strip().startswith(m) for m in _PGP_MARKERS):
                start_idx = i + 1
                continue
            if line.strip().lower().startswith("hash:"):
                start_idx = i + 1
                continue
            if _HEADER_LINE_RE.match(line):
                start_idx = i
                break

    # --- Step 2: find where the header block ends -----------------------
    # Headers end at the first blank line (standard separator between
    # headers and body) or, if it appears earlier, at the line where a PGP
    # block starts (signature or encrypted message used as the body).
    end_idx = len(lines)
    for i in range(start_idx, len(lines)):
        line = lines[i]
        if line.strip() == "":
            end_idx = i
            break
        if any(line.strip().startswith(m) for m in _PGP_MARKERS) or \
           line.strip().startswith("-----BEGIN PGP SIGNATURE-----"):
            end_idx = i
            break

    cleaned = "\n".join(lines[start_idx:end_idx]).strip("\n")
    return cleaned


def analyze_headers(raw_text: str) -> AnalysisResult:
    result = AnalysisResult()

    # Pre-cleanup: strip PGP wrappers and noise before the headers
    # (common in .txt exports from clients like ProtonMail).
    text = _strip_pgp_and_noise(raw_text)

    # The email module can parse both a full message (.eml) and a
    # headers-only block if it ends with a double line break.
    text = text.strip()
    if not text.endswith("\n\n"):
        text += "\n\n"
    msg = email.message_from_string(text, policy=policy.default)

    # --- Base field extraction -------------------------------------------
    from_raw = msg.get("From", "")
    reply_to_raw = msg.get("Reply-To", "")
    return_path_raw = msg.get("Return-Path", "")
    to_raw = msg.get("To", "")
    subject_raw = _decode_header_value(msg.get("Subject", ""))
    message_id = msg.get("Message-ID", "")
    x_mailer = msg.get("X-Mailer", "") or msg.get("User-Agent", "")
    auth_results_all = msg.get_all("Authentication-Results", []) or []
    auth_results = " ; ".join(auth_results_all)
    received_all = msg.get_all("Received", []) or []

    from_name, from_addr = parseaddr(from_raw)
    from_name = _decode_header_value(from_name)
    from_domain = _domain_of(from_addr)
    reply_domain = _domain_of(reply_to_raw)
    return_path_domain = _domain_of(return_path_raw)
    msgid_domain = message_id.split("@")[-1].rstrip(">").lower() if "@" in message_id else ""

    result.fields = {
        "From": from_raw or "(not present)",
        "Display name": from_name or "(no name)",
        "From domain": from_domain or "(unknown)",
        "Reply-To": reply_to_raw or "(not present)",
        "Return-Path": return_path_raw or "(not present)",
        "To": to_raw or "(not present)",
        "Subject": subject_raw or "(no subject)",
        "Message-ID": message_id or "(not present)",
        "X-Mailer / User-Agent": x_mailer or "(not present)",
        "Authentication-Results": auth_results or "(not present)",
        "Received hops": str(len(received_all)),
    }

    # --- Rule 1: SPF / DKIM / DMARC ---------------------------------------
    ar_lower = auth_results.lower()
    if not auth_results:
        result.add(
            "No Authentication-Results header",
            "The message has no Authentication-Results header: SPF/DKIM/DMARC "
            "cannot be verified. Modern mail servers almost always add this "
            "header, so its absence is suspicious.",
            15, "medium",
        )
    else:
        for mech in ("spf", "dkim", "dmarc"):
            m = re.search(rf"{mech}=(\w+)", ar_lower)
            if m:
                verdict = m.group(1)
                if verdict in ("fail", "softfail", "permerror", "temperror"):
                    result.add(
                        f"{mech.upper()} status '{verdict}'",
                        f"{mech.upper()} authentication did not pass.",
                        25, "high",
                    )
                elif verdict == "none":
                    result.add(
                        f"{mech.upper()} not configured",
                        f"The sending domain does not publish a {mech.upper()} record.",
                        10, "low",
                    )

    # --- Rule 2: From vs Return-Path mismatch -----------------------------
    if return_path_domain and from_domain and return_path_domain != from_domain:
        if _similarity(return_path_domain, from_domain) < 0.5:
            result.add(
                "Return-Path does not match From",
                f"From uses '{from_domain}' but Return-Path uses '{return_path_domain}'. "
                "Common in spoofing/spam.",
                20, "high",
            )
        else:
            result.add(
                "Return-Path differs from From (subdomain or similar)",
                f"'{from_domain}' vs '{return_path_domain}'.",
                8, "low",
            )

    # --- Rule 3: From vs Reply-To mismatch --------------------------------
    if reply_domain and from_domain and reply_domain != from_domain:
        result.add(
            "Reply-To points to a different domain",
            f"Replies get redirected from '{from_domain}' to '{reply_domain}'. "
            "A classic technique for diverting replies to an attacker's mailbox.",
            20, "high",
        )

    # --- Rule 4: Message-ID doesn't match the From domain ------------------
    if msgid_domain and from_domain and msgid_domain != from_domain:
        if _similarity(msgid_domain, from_domain) < 0.4:
            result.add(
                "Message-ID from an unrelated domain",
                f"The Message-ID was generated by '{msgid_domain}', not by '{from_domain}'.",
                10, "medium",
            )

    # --- Rule 1b: SPF/DKIM "pass" but for a different domain than From -----
    # An SPF/DKIM 'pass' does NOT mean the email is legitimate: it only
    # confirms that the authenticated domain is allowed to send. If that
    # domain isn't the one shown in 'From', it's spoofing using the
    # attacker's own infrastructure — very common and easy to overlook.
    spf_domain_match = re.search(r"smtp\.mailfrom=([^\s;)]+)", auth_results, re.IGNORECASE)
    spf_auth_domain = spf_domain_match.group(1).split("@")[-1].lower() if spf_domain_match else None
    dkim_domain_match = re.search(r"header\.d=([^\s;)]+)", auth_results, re.IGNORECASE)
    dkim_auth_domain = dkim_domain_match.group(1).lower().rstrip(",;") if dkim_domain_match else None

    def _aligned(d1, d2):
        if not d1 or not d2:
            return True  # not enough data, don't penalize
        return d1 == d2 or d1.endswith("." + d2) or d2.endswith("." + d1)

    if "spf=pass" in ar_lower and spf_auth_domain and from_domain and not _aligned(spf_auth_domain, from_domain):
        result.add(
            "SPF passes, but for a domain different from the visible sender",
            f"SPF passes for '{spf_auth_domain}', not for '{from_domain}' (the domain "
            "shown in 'From'). This means the sending server is allowed to send on "
            "behalf of ITS OWN domain, not that the displayed sender is authentic. "
            "This is a very common phishing technique: the attacker's own "
            "infrastructure, with valid SPF/DKIM, paired with a spoofed 'From'.",
            30, "high",
        )
    elif dkim_auth_domain and from_domain and not _aligned(dkim_auth_domain, from_domain):
        result.add(
            "DKIM valid, but for a domain different from the visible sender",
            f"The DKIM signature belongs to '{dkim_auth_domain}', not to '{from_domain}'.",
            25, "high",
        )

    # --- Rule 5: Known brand impersonation ----------------------------------
    name_lower = from_name.lower()
    # Normalize by removing anything that isn't a letter/digit, to catch
    # obfuscation with dots, spaces or dashes (e.g. "P.A.Y.P.A.L", "P a y pal").
    name_normalized = re.sub(r"[^a-z0-9]", "", name_lower)
    for brand, brand_domain in KNOWN_BRANDS.items():
        brand_key = brand.replace(" ", "")
        if brand_key in name_normalized:
            if brand_domain and from_domain and brand_domain not in from_domain:
                result.add(
                    "Possible brand impersonation",
                    f"The display name mentions '{brand}' but the email comes from "
                    f"'{from_domain}', which does not belong to {brand_domain}.",
                    30, "high",
                )
            if from_domain in FREE_MAIL_DOMAINS:
                result.add(
                    "Brand name + free webmail",
                    f"The name '{brand}' is used from a free email domain "
                    f"('{from_domain}'). Companies rarely email from webmail providers.",
                    25, "high",
                )

    # --- Rule 6: Domain typosquatting ---------------------------------------
    for brand, brand_domain in KNOWN_BRANDS.items():
        if not brand_domain or not from_domain:
            continue
        if _looks_like_typosquat(from_domain, brand_domain):
            result.add(
                "Domain resembling a legitimate one (typosquatting)",
                f"'{from_domain}' suspiciously resembles '{brand_domain}'.",
                30, "high",
            )

    # --- Rule 7: Suspicious TLD -----------------------------------------------
    if from_domain:
        for tld in SUSPICIOUS_TLDS:
            if from_domain.endswith(tld):
                result.add(
                    "High-risk TLD",
                    f"The domain '{from_domain}' uses the '{tld}' extension, "
                    "frequently associated with phishing campaigns (cheap/anonymous registration).",
                    12, "medium",
                )
                break

    # --- Rule 8: Suspicious header encoding -----------------------------------
    for hname in ("Subject", "From"):
        raw_val = msg.get(hname, "")
        if raw_val and "=?" in raw_val and "?=" in raw_val:
            encoded_blocks = len(re.findall(r"=\?[^?]+\?[BbQq]\?[^?]*\?=", raw_val))
            if encoded_blocks >= 3:
                result.add(
                    "Excessive MIME encoding",
                    f"The '{hname}' header uses multiple encoded blocks, "
                    "a tactic used to obfuscate content and evade filters.",
                    10, "low",
                )

    # --- Rule 9: Received chain ------------------------------------------------
    if len(received_all) == 0:
        result.add(
            "No Received headers",
            "There's no trace of the email's path through SMTP servers. May "
            "indicate direct injection, or that an incomplete fragment was pasted.",
            10, "low",
        )
    else:
        ips = re.findall(r"\[?(\d{1,3}(?:\.\d{1,3}){3})\]?", " ".join(received_all))
        private_ip_pattern = re.compile(
            r"^(10\.|172\.(1[6-9]|2\d|3[0-1])\.|192\.168\.|127\.)"
        )
        if ips and private_ip_pattern.match(ips[-1]):
            result.add(
                "Private/internal origin IP",
                f"The first hop reports an internal IP ({ips[-1]}), unusual for "
                "email arriving from the Internet; may indicate forged headers.",
                8, "low",
            )

    # --- Rule 10: Suspicious X-Mailer ------------------------------------------
    if x_mailer:
        suspicious_mailers = ["php", "mass mailer", "bulk", "quick send", "mailer daemon"]
        if any(s in x_mailer.lower() for s in suspicious_mailers):
            result.add(
                "Suspicious sending tool",
                f"X-Mailer/User-Agent indicates '{x_mailer}', often associated with "
                "automated bulk-sending tools.",
                10, "medium",
            )

    # --- Rule 11: Urgency/pressure language in the subject ---------------------
    subj_lower = subject_raw.lower()
    hits = [kw for kw in URGENCY_KEYWORDS if kw in subj_lower]
    if hits:
        result.add(
            "Urgency/pressure language in the subject",
            f"The subject contains phrases typical of social engineering: {', '.join(hits[:4])}.",
            10, "low",
        )

    # --- Rule 12: Generic/hidden recipient ---------------------------------------
    if to_raw:
        to_addrs = getaddresses([to_raw])
        if len(to_addrs) == 1 and to_addrs[0][1]:
            local_part = to_addrs[0][1].split("@")[0].lower()
            if local_part in ("undisclosed-recipients", "recipient", "user", "customer"):
                result.add(
                    "Generic/hidden recipient",
                    "The 'To' field does not identify a real recipient, typical of "
                    "bulk phishing sends.",
                    8, "low",
                )

    # --- Rule 13: The mail provider already flagged it as spam ------------------
    spam_marker_headers = {
        "X-Spam": msg.get("X-Spam", ""),
        "X-Spam-Flag": msg.get("X-Spam-Flag", ""),
        "X-Spam-Status": msg.get("X-Spam-Status", ""),
        "X-Pm-Spam-Action": msg.get("X-Pm-Spam-Action", ""),
    }
    for hname, hval in spam_marker_headers.items():
        if not hval:
            continue
        hval_lower = hval.lower()
        if hval_lower.startswith("yes") or "spam" == hval_lower.strip() or \
           hval_lower.startswith("spam"):
            result.add(
                "The mail provider already flagged this as spam",
                f"The '{hname}' header shows '{hval.strip()}': the receiving server "
                "itself (Gmail, ProtonMail, Outlook, etc.) already classified this "
                "message as spam/phishing before it reached the inbox. This is a "
                "high-confidence signal, even if SPF/DKIM/DMARC pass (the sending "
                "domain may be legitimate but compromised and abused to send spam).",
                35, "high",
            )
            break  # one finding is enough, don't add per repeated header

    # --- Rule 14: Domains with a randomly-generated look (spam automation) -----
    for label_name, domain_val in (
        ("From", from_domain),
        ("Return-Path", return_path_domain),
        ("Message-ID", msgid_domain),
    ):
        random_label = _has_random_looking_label(domain_val)
        if random_label:
            result.add(
                f"Randomly-generated-looking subdomain in {label_name}",
                f"'{random_label}' (inside '{domain_val}') looks like an "
                "auto-generated string with no relation to a real name. Typical of "
                "dynamically-created bulk-mail/spam infrastructure.",
                15, "medium",
            )

    # --- Rule 15: Subject with corrupted encoding (mojibake) --------------------
    if subject_raw.count("?") >= 5:
        result.add(
            "Subject with corrupted characters (mojibake)",
            "The subject contains numerous consecutive '?' symbols, a sign of "
            "broken character encoding or text obfuscated to evade content filters.",
            10, "low",
        )

    # --- Final classification ---------------------------------------------------
    if result.score >= 50:
        result.risk_level = "High"
    elif result.score >= 20:
        result.risk_level = "Medium"
    else:
        result.risk_level = "Low"

    if not result.findings:
        result.add(
            "No relevant indicators found",
            "No suspicious patterns were detected with the current rules. "
            "This does not guarantee the email is legitimate.",
            0, "info",
        )

    return result
